default_config:

homeassistant:
  elevation: 277
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  external_url: "https://inyux67ur6gn8mepb1fqn0bwqeb9pkoy.ui.nabu.casa"

tts:
  - platform: google_translate

alert: !include_dir_merge_named alerts/

automation administration: !include automations/administration.yaml
automation coffee_machine: !include automations/coffee_machine.yaml
automation lights: !include automations/light_automations.yaml

influxdb:
  api_version: 2
  ssl: false
  port: 8086
  host: karlfriedrich
  database: home
  token: !secret influx_token
  bucket: home
  organization: home

http:
  login_attempts_threshold: 5

input_boolean: !include_dir_merge_named input/input_boolean/
input_number: !include_dir_merge_named input/input_number/
input_select: !include_dir_merge_named input/input_select/
input_text: !include_dir_merge_named input/input_text/
input_datetime: !include_dir_merge_named input/input_datetime/

light dining_room: !include dining_room/lights.yaml
light general: !include general/lights.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    custom_components.pyscript: info

lovelace:
  mode: storage
  dashboards:
    lovelace-device:
      mode: yaml
      title: Geräte
      icon: mdi:devices
      show_in_sidebar: true
      filename: dashboards/devices.yaml

mqtt:
  broker: karlfriedrich
  username: !secret mqtt_username
  password: !secret mqtt_password

netatmo:
  client_id: 61702ebecc7f0e0a5a4fb983
  client_secret: gdEeAxrRlsBtAbxwfPIYqk9b5qh9IvL1BxJWqA

notify ios:
  - name: iOS
    platform: group
    services:
      - service: mobile_app_guidos_iphone

recorder:
  db_url: !secret maria_db_url

pyscript: !include pyscript/config.yaml

script zigbee2mqtt: !include zigbee2mqtt/scripts.yaml

sensor zigbee2mqtt: !include zigbee2mqtt/sensors.yaml
sensor mobile_alerts: !include mobile_alerts_sensors.yaml

switch general: !include zigbee2mqtt/switches.yaml
switch indoor_pool: !include indoor_pool/switches.yaml

template: !include_dir_merge_list template/

rest_command:
  refresh_duckdns_ip:
    url: >
      {{ "https://www.duckdns.org/update?domains=" + states('sensor.duckdns_domain') + "&token=" + states('sensor.duckdns_access_token') + "&ip=" + states("sensor.fritz_box_7590_external_ip") }}"
    method: GET

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120
  reactivated_oxygen_pump_timer:
    duration: "00:00:00"

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 19
