default_config:

homeassistant:
  elevation: 277
  time_zone: Europe/Berlin
  customize: !include customize.yaml

tts:
  - platform: google_translate

automation zigbee2mqtt: !include zigbee2mqtt/automations.yaml
automation coffee_machine: !include automations/coffee_machine.yaml
automation lights: !include automations/light_automations.yaml

influxdb:
  api_version: 2
  ssl: false
  port: 8086
  host: karlfriedrich
  database: home
  token: !secret influx_token
  bucket: home
  organization: home

http:
  login_attempts_threshold: 5

input_boolean: !include_dir_merge_named input/input_boolean/
input_number: !include_dir_merge_named input/input_number/
input_select: !include_dir_merge_named input/input_select/
input_text: !include_dir_merge_named input/input_text/
input_datetime: !include_dir_merge_named input/input_datetime/

light dining_room: !include dining_room/lights.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info

lovelace:
  mode: storage
  dashboards:
    lovelace-device:
      mode: yaml
      title: Geräte
      icon: mdi:devices
      show_in_sidebar: true
      filename: dashboards/devices.yaml

mqtt:
  broker: karlfriedrich
  username: !secret mqtt_username
  password: !secret mqtt_password

recorder:
  db_url: !secret maria_db_url

script zigbee2mqtt: !include zigbee2mqtt/scripts.yaml

sensor zigbee2mqtt: !include zigbee2mqtt/sensors.yaml
sensor mobile_alerts: !include mobile_alerts_sensors.yaml

switch general: !include zigbee2mqtt/switches.yaml

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 19
