- platform: group
  name: Lower Floor Living Quarters Lights
  entities:
    - light.esszimmer_1
    - light.esszimmer_2
    - light.esszimmer_3
    - light.esszimmer_4
    - light.wohnzimmer_buffet_lampe
    - light.hue_iris_bubble
    - light.hue_white_lamp_1
    - light.hue_white_lamp_1_2
    - light.light_3
    - light.light_4
    - light.fruhstuckszimmer_wandlampe_1
    - light.breakfast_room_wall_light_2
    - light.breakfast_room_wall_light_3
    - light.esszimmer_vertico
- platform: group
  name: Breakfast Room Lights
  entities:
    - light.fruhstuckszimmer_wandlampe_1
    - light.breakfast_room_wall_light_2
    - light.breakfast_room_wall_light_3
- platform: group
  name: Upper Floor Living Quarters Lights
  entities:
    - light.light_5

- platform: group
  name: Garden Lights
  entities:
    - light.hue_lily_outdoor_spotlight_1
    - light.hue_lily_outdoor_spotlight_2
    - light.hue_lily_outdoor_spotlight_3
    - light.hue_lily_outdoor_spotlight_4
    - light.hue_lily_outdoor_spotlight_5
    - light.hue_lily_outdoor_spotlight_6
    - light.outdoor_barbecue_light
