- alias: Turn on coffee machine on weekdays
  trigger:
    - platform: time
      at: input_datetime.coffee_machine_week_day_on_time
  condition:
    alias: "WeekDay"
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.steckdose_kaffeemaschine
    - delay: "00:00:03"
    - service: switch.turn_on
      target:
        entity_id: switch.steckdose_kaffeemaschine

- alias: Turn off coffee machine on weekdays
  trigger:
    - platform: time
      at: input_datetime.coffee_machine_week_day_off_time
  condition:
    alias: "WeekDay"
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.steckdose_kaffeemaschine
    - delay: "00:00:03"
    - service: switch.turn_off
      target:
        entity_id: switch.steckdose_kaffeemaschine
