- alias: Turn on coffee machine on weekdays
  trigger:
    - platform: time
      at: input_datetime.coffee_machine_week_day_on_time
  condition:
    alias: "WeekDay"
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      target:
        entity_id: light.hue_smart_plug_1

- alias: Turn on coffee machine on weekday afternoons
  trigger:
    - platform: time
      at: input_datetime.coffee_machine_week_day_afternoons_on_time
  condition:
    alias: "WeekDay"
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
  action:
    - service: light.turn_on
      target:
        entity_id: light.hue_smart_plug_1

- alias: Turn off coffee machine on weekdays
  trigger:
    - platform: time
      at: input_datetime.coffee_machine_week_day_off_time
  condition:
    alias: "WeekDay"
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_off
      target:
        entity_id: light.hue_smart_plug_1

- alias: Turn off coffee machine on weekday afternoons
  trigger:
    - platform: time
      at: input_datetime.coffee_machine_week_day_afternoons_off_time
  condition:
    alias: "WeekDay"
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
  action:
    - service: light.turn_off
      target:
        entity_id: light.hue_smart_plug_1
