homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://karlfriedrich
  user: zigbee2mqtt
  password: "!secret mqtt_password"
serial:
  port: /dev/ttyUSB0
advanced:
  channel: 12
devices:
  "0x00124b00077d28e9":
    friendly_name: Oxygen Pump Switch 1
  "0x00124b0002ccc756":
    friendly_name: Oxygen Pump Switch 2
  "0x00178801001235e3":
    friendly_name: Hue Iris Bubble
  "0x001788010802b61a":
    friendly_name: Hue Smart Button 1
  "0xbc33acfffe64ad55":
    friendly_name: Repeater 1
  "0x00124b002510b884":
    friendly_name: Door Sensor 1
  "0x00124b002510b731":
    friendly_name: Door Sensor 4
  "0x00124b002512fceb":
    friendly_name: Door Sensor 3
  "0x00124b00251073fe":
    friendly_name: Door Sensor 2
  "0x0017880109e65105":
    friendly_name: Hue Iris Bubble Tragbar
